version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: maint
    schedule:
      interval: "monthly"
    pull-request-branch-name:
      separator: "-"
