repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: ''
    hooks:
    -   id: end-of-file-fixer
        exclude: '(?:.*\.(ai|txt)|extern/*)'
    -   id: trailing-whitespace
        exclude: '(?:.*\.(ai|txt)|extern/|setup.cfg*)'
    -   id: debug-statements
-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]
        args:
        - --show-source
-   repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
    -   id: cmake-format
