version: 2.1

orbs:
  win: circleci/windows@2.2.0  # Enables Windows executors

references:
  container_manylinux: &container_manylinux
    docker:
      - image: quay.io/pypa/manylinux1_x86_64
    working_directory: ~/ci/freud

  container_macos: &container_macos
    macos:
      xcode: "12.0.0"
    working_directory: ~/ci/freud

  load_code: &load_code
    checkout

  load_code_centos: &load_code_centos
    # For use with old OS that doesn't support clone over ssh
    run:
      name: Checkout repository without ssh
      command: |
        cd ~/ci/freud
        git clone ${CIRCLE_REPOSITORY_URL} .
        if [ -n "$CIRCLE_TAG" ]
        then
          git reset --hard "$CIRCLE_SHA1"
          git checkout -q "$CIRCLE_TAG"
        elif [ -n "$CIRCLE_BRANCH" ]
        then
          git reset --hard "$CIRCLE_SHA1"
          git checkout -q -B "$CIRCLE_BRANCH"
        fi

  update_submodules: &update_submodules
    run:
      name: Update submodules
      command: |
        git submodule update --init

  get_requirements: &get_requirements
    run:
      name: Install dependencies
      command: |
        # Since we're testing against a very old cmake, wheels may not exist
        # for newer Python versions (currently this is true for Python3.8, will
        # be true for 3.9 as well). We will need to build the cmake wheels from
        # a tarball in this case, and cmake depends on scikit-build, so we
        # install skbuild separately here. Note that newer cmake versions build
        # universal wheels instead, so once we upgrade to cmake >= 3.14 we won't
        # be dependent on them updating wheels for specific new Python versions.
        python${PYVER} -m pip install --user scikit-build==0.10.0
        python${PYVER} -m pip install --user -r requirements-testing.txt

  get_conda_requirements: &get_conda_requirements
    run:
      name: Install dependencies with conda
      command: |
        conda config --set always_yes yes --set changeps1 no
        conda config --add channels conda-forge
        conda update -q conda certifi
        conda install python pip tbb tbb-devel
        conda update --all
        # Install from PyPI instead of conda-forge for consistency with Linux.
        # For some reason, the SSL certificates used by pip aren't correct, even with certifi.
        curl -O https://curl.haxx.se/ca/cacert.pem
        export PIP_CERT="$PWD/cacert.pem"
        python${PYVER} -m pip install --progress-bar off -U -r requirements-testing.txt
        # Install cmake >=3.14 to support Visual Studio 2019 generator
        python${PYVER} -m pip install --progress-bar off -U cmake~=3.14

  get_pre_commit_requirements: &get_pre_commit_requirements
    run:
      name: Install pre-commit dependencies
      command: |
        python${PYVER} -m pip install --user -r requirements-precommit.txt

  pre-test-checks: &pre-test-checks
    run:
      name: Run all static checks
      command: |
        # Changes to environment variables (like PATH) don't persist between
        # run steps in CircleCI, so we specify the full path to pre-commit
        # explicitly here.
        python${PYVER} -m pre_commit run --all-files

  build: &build
    run:
      name: Build
      command: |
        python${PYVER} --version
        # Max 4 threads to not overtax CI.
        python${PYVER} setup.py build_ext --inplace -- -DCOVERAGE=ON -- -j 4 -v

  build_windows: &build_windows
    run:
      name: Build with MSVC
      command: |
        python${PYVER} --version
        python${PYVER} setup.py build_ext --inplace -- -G "Visual Studio 16 2019" -DCOVERAGE=ON

  test: &test
    run:
      name: Run unit tests
      command: |
          python${PYVER} -m unittest discover tests -v

  test_cov: &test_cov
    run:
      name: Run unit tests with coverage
      command: |
          python${PYVER} -m coverage run -m unittest discover tests -v
          bash <(curl -s https://codecov.io/bash)

  store: &store
    store_artifacts:
      path: test-reports
      destination: test-reports

  benchmark: &benchmark
    run:
      name: Run benchmarks
      command: |
          echo 'export PYTHONPATH=$PYTHONPATH:.' >> $BASH_ENV
          echo 'export BENCHMARK_NPROC=2' >> $BASH_ENV
          source $BASH_ENV
          BENCHSCR="benchmarks/benchmarker.py"
          echo "Running benchmark on current HEAD"
          python${PYVER} "$BENCHSCR" run

  comparison: &comparison
    run:
      name: Compare benchmark with origin/master
      command: |
          echo "Comparing with origin/master"
          git reset --hard origin/master
          echo "PYVER=${PYVER}"
          echo 'export PYTHONPATH=$PYTHONPATH:.' >> $BASH_ENV
          echo 'export BENCHMARK_NPROC=2' >> $BASH_ENV
          source $BASH_ENV
          # Max 4 threads to not overtax CI.
          python${PYVER} setup.py build_ext --inplace -- -DCOVERAGE=ON -- -j 4
          git checkout "${CIRCLE_SHA1}" -- benchmarks/
          BENCHSCR="benchmarks/benchmarker.py"
          echo "Running benchmark on origin/master"
          python${PYVER} "$BENCHSCR" run
          python${PYVER} "$BENCHSCR" compare origin/master "${CIRCLE_SHA1}"

  store_benchmarks: &store_benchmarks
    store_artifacts:
      path: benchmarks/reports
      destination: benchmarks-reports

  build_and_test_linux: &build_and_test_linux
    steps:
      - *load_code
      - *update_submodules
      - *get_requirements
      - *build
      - *test
      - *store

  build_and_test_linux_with_cov: &build_and_test_linux_with_cov
    steps:
      - *load_code
      - *update_submodules
      - *get_requirements
      - *build
      - *test_cov
      - *store

  build_and_test_windows: &build_and_test_windows
    steps:
      - *load_code
      - *update_submodules
      - *get_conda_requirements
      - *build_windows
      - *test_cov
      - *store

  load_check_style: &load_check_style
    steps:
      - *load_code
      - *update_submodules
      - *get_pre_commit_requirements
      - *pre-test-checks

  build_and_benchmark: &build_and_benchmark
    steps:
      - *load_code
      - *update_submodules
      - *get_requirements
      - *build
      - *benchmark
      - *comparison
      - *store_benchmarks

  build_linux_test_wheels: &build_linux_test_wheels
    steps:
      - run:
          name: Install software
          working_directory: /root/code
          command: yum install -y openssh-clients
      - *load_code_centos
      - *update_submodules
      - run:
          name: Compile Linux wheels
          command: |
            bash .circleci/deploy-linux.sh testpypi

  build_linux_wheels: &build_linux_wheels
    steps:
      - run:
          name: Install software
          working_directory: /root/code
          command: yum install -y openssh-clients
      - *load_code_centos
      - *update_submodules
      - run:
          name: Compile Linux wheels
          command: |
            bash .circleci/deploy-linux.sh pypi

  build_macos_test_wheels: &build_macos_test_wheels
    steps:
      - *load_code
      - *update_submodules
      - run:
          name: Compile Mac wheels
          command: |
            bash .circleci/deploy-macos.sh testpypi

  build_macos_wheels: &build_macos_wheels
    steps:
      - *load_code
      - *update_submodules
      - run:
          name: Compile Mac wheels
          command: |
            bash .circleci/deploy-macos.sh pypi

jobs:
  check-style:
    docker:
      - image: glotzerlab/ci:2020.10-clang10_py38
    working_directory: ~/ci/freud
    environment:
      PYVER: "3.8"
    <<: *load_check_style

  linux-python-38:
    docker:
      - image: glotzerlab/ci:2020.10-py38
    working_directory: ~/ci/freud
    environment:
      PYVER: "3.8"
    <<: *build_and_test_linux

  linux-python-37:
    docker:
      - image: glotzerlab/ci:2020.10-py37
    working_directory: ~/ci/freud
    environment:
      PYVER: "3.7"
    <<: *build_and_test_linux_with_cov

  linux-python-36:
    docker:
      - image: glotzerlab/ci:2020.10-py36
    working_directory: ~/ci/freud
    environment:
      PYVER: "3.6"
    <<: *build_and_test_linux

  windows-python-37:
    executor:
      name: win/default
      shell: bash.exe
    environment:
      PYVER: ""  # Windows CI image doesn't have aliases for python3.7
      TBB_INCLUDE: "C:\\tools\\miniconda3\\Library\\include"
      TBB_LINK: "C:\\tools\\miniconda3\\Library\\lib"
    <<: *build_and_test_windows

  test-deploy-pypi-linux:
    environment:
      # Force clone over https instead of ssh.
      CIRCLE_REPOSITORY_URL: https://github.com/glotzerlab/freud
    <<: *container_manylinux
    <<: *build_linux_test_wheels

  test-deploy-pypi-macos:
    <<: *container_macos
    <<: *build_macos_test_wheels

  deploy-pypi-linux:
    environment:
      # Force clone over https instead of ssh.
      CIRCLE_REPOSITORY_URL: https://github.com/glotzerlab/freud
    <<: *container_manylinux
    <<: *build_linux_wheels

  deploy-pypi-macos:
    <<: *container_macos
    <<: *build_macos_wheels

  benchmarks:
    docker:
      - image: glotzerlab/ci:2020.01-py38
    working_directory: ~/ci/freud
    environment:
      PYVER: "3.8"
    <<: *build_and_benchmark

workflows:
  version: 2
  test:
    jobs:
      - check-style
      - linux-python-38:
          requires:
            - check-style
      - linux-python-37:
          requires:
            - check-style
      - linux-python-36:
          requires:
            - check-style
      - windows-python-37:
          requires:
            - check-style
# Disabled benchmarks on CI - they currently take too much work
#     - benchmarks:
#         requires:
#           - linux-python-38
      - test-deploy-pypi-macos:
          filters:
            branches:
              only: /release\/.*/
          requires:
            - check-style
            - linux-python-38
            - linux-python-37
            - linux-python-36
            - windows-python-37
      - test-deploy-pypi-linux:
          filters:
            branches:
              only: /release\/.*/
          requires:
            - check-style
            - linux-python-38
            - linux-python-37
            - linux-python-36
            - windows-python-37

  deploy:
    jobs:
      - deploy-pypi-macos:
          filters:
              tags:
                only: /^v.*/
              branches:
                ignore: /.*/
      - deploy-pypi-linux:
          filters:
              tags:
                only: /^v.*/
              branches:
                ignore: /.*/
