name: Feature Request
description: Suggest a new feature for freud
body:
  - type: textarea
    attributes:
      label: Problem
      description: Is your feature request related to a problem? Please describe.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: Please provide a clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
        label: Alternatives
        description: Describe any alternatives you have considered.
  - type: dropdown
    attributes:
      label: Developer
      description: Who should implement the new feature?
      options:
        - I can!
        - I can, but I'll need some help/guidance.
        - Someone else will need to implement this feature.
    validations:
      required: true
