name: Run Benchmarks

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types: [opened, labeled, reopened, synchronize]

  # trigger on request
  workflow_dispatch:

jobs:
  # start the runners on jetstream2
  start_action_runners:
    name: Start action runners
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'benchmark') }}
    steps:
      - uses: glotzerlab/jetstream2-admin/start@v1.0.0
        with:
          OS_APPLICATION_CREDENTIAL_ID: ${{ secrets.OS_APPLICATION_CREDENTIAL_ID }}
          OS_APPLICATION_CREDENTIAL_SECRET: ${{ secrets.OS_APPLICATION_CREDENTIAL_SECRET }}

  run_benchmarks:
    name: Run the freud benchmarks
    runs-on: jetstream2
    container:
      image: glotzerlab/ci:2022.05-gcc10_py310
    if: ${{ contains(github.event.pull_request.labels.*.name, 'benchmark') }}
    steps:
      - name: Clean workspace
        run: |
            rm -rf ./*

      - name: Checkout Code
        uses: actions/checkout@v3.0.2
        with:
          submodules: true

      - name: Build and install freud
        shell: bash -l {0}
        run: |
            pip install -r .github/workflows/conda-envs/requirements-test.txt
            which python
            python setup.py install --user

      - name: Run benchmarks on pull request commit
        shell: bash -l {0}
        run: |
          echo "Print working directory"
          cd benchmarks
          pwd
          echo "Running benchmarks on current HEAD"
          python benchmarker.py run
        env:
          BENCHMARK_NPROC: 2
            #PYTHONPATH: ./benchmarks/

      - name: Run benchmarks on master and compare
        shell: bash -l {0}
        run: |
          echo "Rebuild freud on the master branch"
          git reset --hard origin/master
          python setup.py install --user

          echo "Run benchmarks on the master branch"
          python benchmarks/benchmarker.py run
          python benchmarks/benchmarker.py compare origin/master ${{ github.sha }}
        env:
          BENCHMARK_NPROC: 2
          PYTHONPATH: $PYTHONPATH:./benchmarks/

      # TODO old circleci script stored benchmarks as well, maybe add that here?
