name: Run Unit Tests

# Remove this for now, circleci is getting in the way with tests failing
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  # trigger on pull requests
  pull_request:

  # trigger on all commits to master and tagged commits
  push:
    branches:
      - "master"
    tags:
      - "v*"

  # trigger on request
  workflow_dispatch:

jobs:
  run_tests:
    name: Run tests on ${{ matrix.os }} with python ${{ matrix.pyver-reqs.pyver }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        pyver-reqs: [ {pyver: '3.10', reqs: 'test_env.yaml'} ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.4
        with:
          path: freud
          submodules: true

      - name: Create Python Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python_version: ${{ matrix.pyver-reqs.pyver }}
          environment_file: freud/.github/workflows/conda-envs/${{ matrix.pyver-reqs.reqs }}
          channels: conda-forge,defaults
          activate_environment: test
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true

      - name: Build and Install freud
        shell: bash -l {0}
        run: |
          cd freud/
          conda list
          python setup.py install --user

      - name: Run Tests
        shell: bash -l {0}
        run: |
          pytest tests/ -v
